# Generated by Django 6.0.4 on 2026-05-05 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='color',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='initials',
        ),
    ]
