# Generated by Django 6.0.4 on 2026-05-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_remove_stock_color_remove_stock_exchange_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprice',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='change_pct',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8),
        ),
    ]
