# Generated by Django 6.0.4 on 2026-05-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_dailyprice_change_alter_dailyprice_change_pct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyprice',
            options={'ordering': ['-date', '-updated_at']},
        ),
        migrations.AlterUniqueTogether(
            name='dailyprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dailyprice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
