# Generated by Django 6.0.4 on 2026-05-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_dailyprice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
