# Generated by Django 6.0.4 on 2026-05-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_stock_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='fundamentals_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
