# Generated by Django 6.0.4 on 2026-05-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_stock_fundamentals_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='fundamentals_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
